### ISSUE TITLE
Project that uses .NET Standard TP fails to compile

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.TypeProviders.SDK#142]
I'm trying to port FSharp.Configuration to .NET Standard 2.0, see https://github.com/fsprojects/FSharp.Configuration/compare/master...vasily-kirichenko:net-standard-2.0?expand=1

The TP itself is built successfully, but the testing project is not:

>  The type provider 'D:\WLCR\github\FSharp.Configuration\src\FSharp.Configuration\bin\Debug\netstandard2.0\FSharp.Configuration.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Configuration' which cannot be loaded or doesn't exist. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

**Comment by dsyme** [comment]
@vasily-kirichenko Great, thanks for doing this - updating real-world type providers is very important to help flush out issues

I believe the solution is to ship the facade DLL netstandard.dll in the nuget package.  For now my understanding is that that can go alongside the runtime and design-time DLLs, but equally it might be that we have to have https://github.com/Microsoft/visualfsharp/issues/3736 in place (see sample nuget package layouts in that issue)

**Comment by dsyme** [comment]
@vasily-kirichenko BTW I pushed a bug fix to the TPSDK, so please paket update again

**Comment by vasily-kirichenko** [comment]
I have this

![image](https://user-images.githubusercontent.com/873919/31495051-a6b251fe-af5e-11e7-99fd-b4a161766960.png)

and add a reference in the test project

```xml
<ItemGroup>
    <Reference Include="FSharp.Configuration, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null">
      <HintPath>..\..\src\FSharp.Configuration\bin\Debug\netstandard2.0\FSharp.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51">
      <HintPath>..\..\packages\NETStandard.Library\build\netstandard2.0\ref\netstandard.dll</HintPath>
    </Reference>
  </ItemGroup>
```

The same error still exists.

**Comment by vasily-kirichenko** [comment]
@dsyme Updated. Same error.

**Comment by vasily-kirichenko** [comment]
Maybe I'm doing testing in a wrong way? I mean maybe it's necessary to build a package and reference it? I just reference assemblies.

**Comment by dsyme** [comment]
@vasily-kirichenko I'll take a look.  Could you send a PR to this repo with the work so far please?  Thanks

**Comment by vasily-kirichenko** [comment]
@dsyme done https://github.com/fsprojects/FSharp.Configuration/pull/133

**Comment by dsyme** [comment]
Thanks

**Comment by dsyme** [comment]
This specific problem has been fixed
