### ISSUE TITLE
System.NullReferenceException when user targets to .NET Standard 2.0

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharp.TypeProviders.SDK#177]
When a .NET Standard 2.0 erasing type provider is used in a library project that targets .NET Standard 2.0, the ProvidedTypes.fs type ProvidedTypesContext method Create throws an exception in line:

```fsharp
    with e ->
        failwith (sprintf "Invalid host of cross-targeting type provider. Exception: %A" e)

```

...and it's a System.NullReferenceException:

```
Invalid host of cross-targeting type provider. Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at <StartupCode$FSharp-Data-SqlProvider>.$ProvidedTypes.referencedAssemblyPaths@8509.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
      at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
	  at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
	  at ProviderImplementation.ProvidedTypes.ProvidedTypesContext.Create(TypeProviderConfig cfg, FSharpOption`1 assemblyReplacementMap)
```

.NET CoreApp 2.0 target seems to work ok.

**Comment by Thorium** [comment]
The base is null:
```fsharp
let baseObj = tcImports.GetProperty("Base")
```

**Comment by Thorium** [comment]
Just skipping the base object

```
    [ for dllInfo in dllInfos.GetElements() -> (dllInfo.GetProperty("FileName") :?> string)
      if baseObj <> null then
          for dllInfo in baseObj.GetProperty("Value").GetField("dllInfos").GetElements() -> (dllInfo.GetProperty("FileName") :?> string) 
    ]
```

...is not a working solution, the compiler will hang.

**Comment by dsyme** [comment]
@Thorium Could you add a sample project that repros this?  The test suite does have a sample of a .NET Standard 2.0 type provider (or it is in #175)

**Comment by Thorium** [comment]
This might be ok, if ProvidedTypesContext Create is actually expired and not called anymore, I wasn't using the latest SDK version.
I was able to add netstandard2.0 to examples ComboProvider.Tests.fsproj and it seems to build still.
`<TargetFrameworks>netcoreapp2.0;net461;netstandard2.0</TargetFrameworks>`

**Comment by Thorium** [comment]
I tried to update to latest SDK but this still fails.

Branch is here https://github.com/fsprojects/SQLProvider/tree/sdk-update

1) Run build.cmd to build the SQLProvider
2) Copy&overwrite SQLProvider\bin\netstandard2.0 content to your nuget cache e.g. C:\Users\myName\.nuget\packages\SQLProvider\1.1.22\lib\netstandard2.0
3) Try running build on one of the test projects, e.g. SQLProvider\tests\SqlProvider.Core.Tests

Now, the call to Create comes from constructor, which I tried to imitate from this projects examples\ComboProvider like this:
```fsharp
[<TypeProvider>]
type SqlTypeProvider(config: TypeProviderConfig) as this =     
    inherit TypeProviderForNamespaces(config, [("FSharp.Data.Sql", "FSharp.Data.Sql")])
```

**Comment by dsyme** [comment]
Fixed by #179

**Comment by Thorium** [comment]
Yes, not fixed. Any ideas how could I go further? I think -v maybe fail to some other place than without it.

```
C:\git\SQLProvider\tests\SqlProvider.Core.Tests\MySql>dotnet build -v
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

C:\git\SQLProvider\tests\SqlProvider.Core.Tests\MySql>dotnet run
C:\Program Files\dotnet\sdk\2.0.2\FSharp\Microsoft.FSharp.Targets(224,9): error MSB6006: "fsc.exe" exited with code -1073741571. [C:\git\SQLProvider\tests\SqlProvider.Core.Tests\MySql\SqlProvider.Core.Tests.fsproj]

The build failed. Please fix the build errors and run again.

C:\git\SQLProvider\tests\SqlProvider.Core.Tests\MySql>
```

**Comment by Thorium** [comment]
I was hoping VS 15.5 would fix things, but no luck.

**Comment by Thorium** [comment]
I was thinking that the problem is this (`ProvidedTypes.fs`):
```fsharp
        let handler = ResolveEventHandler(fun _ args -> this.ResolveAssembly(args))
        do AppDomain.CurrentDomain.add_AssemblyResolve handler

//.... cut cut cut ...///

        default __.ResolveAssembly(args) =
            let expectedName = (AssemblyName(args.Name)).Name + ".dll"
            let expectedLocationOpt =
                probingFolders
                |> Seq.map (fun f -> Path.Combine(f, expectedName))
                |> Seq.tryFind File.Exists
            match expectedLocationOpt with
            | Some f -> Assembly.LoadFrom f
            | None -> null
```

...as clearly calling Assembly.LoadFrom inside ResolveEventHandler should lead to stack overflow exception as described [here](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/resolve-assembly-loads#what-the-event-handler-should-not-do).

However, it seems that F# compiler manages to call the constructor, and also manages to call `member __.GetNamespaces()` of type TypeProviderForNamespaces but fails before calling `member __.GetStaticParameters(ty)`.

**Comment by vanceism7** [comment]
Hey @Thorium, any update on the state of this issue? I believe this is the same problem I've ran into when trying to use SQL provider

**Comment by Thorium** [comment]
Yes, the latest version doesn't crash to a null-reference-exception but throws a stack-overflow-exception after a GetType-TryBindType-GetType-loop with "System.Object". 

I made a fix in PR #183 but I expect we still have a problem here: In Linux environment with Core App the TypeProvider library is compiled with Mono and used with .NET Core on runtime. But there is a difference that "System.Object" is referenced from mscorlib.dll in Mono and netstandard.dll in Core.

After this PR what happens is that we get further in the compilation, but as the type-provider uses e.g. FSharp.Core, during the compilation it's loaded with reflection. Reflection tries to load all the dependency libraries, which are clear in .NET Framwork and .NET Core, but not with .NET Standard. In F# core there is e.g. alias bigint which is a dependency to Int64 loaded from which library: mscorlib.dll or netstandard.dll? Currently the build fails there.

**Comment by Thorium** [comment]
Added a PR that contains .NET Standard tests to demonstrate the problem.

**Comment by vanceism7** [comment]
Gotcha, so this is a .net standard issue then. Thanks for the info!
